import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "@/styles/globals.css";

// Components
import Navbar from "@/components/Navbar/NavBar";

const geologica = Geologica({
  subsets: ['latin'],
  weight: ['300'],
  variable: '--font-geologica',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Ai Skin Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="mn">
    <body
    className={`${geologica.className} antialiased`}
    >
    <div className="w-full fixed z-30">
      <Navbar />
    </div>
    {children}
    </body>
  </html>
  );
}
